# Generated by Django 4.2.1 on 2023-05-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('isVegan', models.BooleanField()),
                ('isVegetarian', models.BooleanField()),
                ('servingSize', models.CharField(max_length=20, null=True)),
                ('servingUnit', models.CharField(max_length=20, null=True)),
                ('calories', models.CharField(max_length=20, null=True)),
                ('caloriesFromFat', models.CharField(max_length=20, null=True)),
                ('totalFat', models.CharField(max_length=20, null=True)),
                ('transFat', models.CharField(max_length=20, null=True)),
                ('cholesterol', models.CharField(max_length=20, null=True)),
                ('sodium', models.CharField(max_length=20, null=True)),
                ('totalCarbohydrates', models.CharField(max_length=20, null=True)),
                ('dietaryFiber', models.CharField(max_length=20, null=True)),
                ('sugars', models.CharField(max_length=20, null=True)),
                ('protein', models.CharField(max_length=20, null=True)),
                ('vitaminA', models.CharField(max_length=20, null=True)),
                ('vitaminC', models.CharField(max_length=20, null=True)),
                ('calcium', models.CharField(max_length=20, null=True)),
                ('iron', models.CharField(max_length=20, null=True)),
                ('saturatedFat', models.CharField(max_length=20, null=True)),
                ('isEatWell', models.BooleanField()),
                ('isPlantForward', models.BooleanField()),
                ('isWholeGrain', models.BooleanField()),
            ],
        ),
    ]
